public class Covid19CountrySummary {
    @AuraEnabled
   public string Country;
    @AuraEnabled
    public string CountrySlug;
    @AuraEnabled
          public string NewConfirmed;
    @AuraEnabled
           public integer TotalConfirmed;
    @AuraEnabled
    public string NewDeaths;
    @AuraEnabled
    public string TotalDeaths;
    @AuraEnabled
    public string NewRecovered;
    @AuraEnabled
    public string TotalRecovered;

}